"""Functional connectivity utilities for MEA spike data.

The module starts from per-channel spike frames generated by the spike-detection
pipeline, converts them to spike times, and builds channel-by-channel
connectivity matrices using common MEA-friendly measures:

- binned spike-count correlation;
- Spike Time Tiling Coefficient (STTC);
- cross-correlogram peak and lag.

Expected input folders look like::

    spikes/<recording>/frames_ch0.npy
    spikes/<recording>/frames_ch1.npy
    spikes/<recording>/label_ch1.npy

Frame arrays contain spike frame indices for one channel. Optional label arrays
can be used to keep only specific spike polarities or detector labels.

All public functions use channel numbers as matrix/table identifiers. Matrix
row and column order is always returned explicitly through the ``channels``
output so downstream code can map matrix indices back to MEA electrodes.
"""

from pathlib import Path
import time

import numpy as np
import pandas as pd


def _as_path(PathValue):
    """Return a normalized ``Path`` while accepting strings and Path objects."""
    return Path(PathValue).expanduser()


def _channel_from_name(PathValue):
    """Extract the integer channel id from names such as ``frames_ch123.npy``."""
    Stem = Path(PathValue).stem
    try:
        return int(Stem.split("ch")[-1])
    except ValueError:
        return None


def LoadSpikeFrames(SpikeDir, IncludeLabels=None):
    """Load channel spike frames from a processed ``spikes/<recording>`` folder.

    Parameters
    ----------
    spike_dir : str or pathlib.Path
        folder containing ``frames_ch*.npy`` and optionally ``label_ch*.npy``.
    include_labels : list[int], optional
        if provided, keep only spikes whose detector label is in this list.
        Use ``None`` to keep all detected spikes.

    Returns
    -------
    dict
        ``{channel: frames}``, where each value is a sorted 1D integer array.
    """
    SpikeDir = _as_path(SpikeDir)
    IncludeLabels = None if IncludeLabels is None else set(IncludeLabels)
    Spikes = {}

    for FramePath in sorted(SpikeDir.glob("frames_ch*.npy")):
        Channel = _channel_from_name(FramePath)
        if Channel is None:
            continue

        Frames = np.asarray(np.load(FramePath)).reshape(-1).astype(int)
        LabelPath = FramePath.with_name(f"label_ch{Channel}.npy")
        if IncludeLabels is not None and LabelPath.exists():
            Labels = np.asarray(np.load(LabelPath)).reshape(-1).astype(int)
            N = min(len(Frames), len(Labels))
            Frames = Frames[:N][np.isin(Labels[:N], list(IncludeLabels))]

        Spikes[Channel] = np.sort(Frames)

    if not Spikes:
        raise FileNotFoundError(f"No frames_ch*.npy files found in {SpikeDir}.")

    return Spikes


def FramesToSeconds(SpikeFrames, SamplingRate):
    """Convert spike frame indices to spike times in seconds.

    Parameters
    ----------
    spike_frames : dict
        Mapping ``{channel: frames}``, as returned by :func:`LoadSpikeFrames`.
    sampling_rate : float
        Sampling rate in Hz used during acquisition.

    Returns
    -------
    dict
        Mapping ``{channel: spike_times_seconds}``.
    """
    if SamplingRate <= 0:
        raise ValueError("sampling_rate must be positive.")
    return {
        Channel: np.asarray(Frames, dtype=float) / float(SamplingRate)
        for Channel, Frames in SpikeFrames.items()
    }


def BinSpikeCounts(SpikeTimes, BinSize, Duration=None, Channels=None):
    """Bin spike times into a channel-by-time count matrix.

    Parameters
    ----------
    spike_times : dict
        ``{channel: spike_times_seconds}``.
    bin_size : float
        bin size in seconds.
    duration : float, optional
        recording duration in seconds. If omitted, inferred from the latest spike.
    channels : list[int], optional
        channel order. If omitted, sorted channel keys are used.

    Returns
    -------
    tuple
        ``(counts, channels, bin_edges)``.
    """
    if BinSize <= 0:
        raise ValueError("bin_size must be positive.")

    Channels = sorted(SpikeTimes) if Channels is None else list(Channels)
    if Duration is None:
        MaxTimes = [np.max(Times) for Times in SpikeTimes.values() if len(Times) > 0]
        Duration = max(MaxTimes) if MaxTimes else BinSize

    BinEdges = np.arange(0, Duration + BinSize, BinSize)
    Counts = np.zeros((len(Channels), len(BinEdges) - 1), dtype=float)
    for Row, Channel in enumerate(Channels):
        Counts[Row], _ = np.histogram(SpikeTimes.get(Channel, []), bins=BinEdges)

    return Counts, Channels, BinEdges


def SpikeCountCorrelation(SpikeTimes, BinSize=0.05, Duration=None, Channels=None):
    """Compute Pearson correlation between binned channel spike-count trains.

    Spike times are first binned with :func:`BinSpikeCounts`. The returned
    correlation matrix has one row/column per channel and a zero diagonal.

    Returns
    -------
    tuple
        ``(matrix, channels, counts, bin_edges)`` where ``matrix`` is the
        channel-by-channel correlation matrix, ``counts`` is the channel-by-bin
        spike-count matrix, and ``bin_edges`` are the histogram bin edges.
    """
    Counts, Channels, BinEdges = BinSpikeCounts(
        SpikeTimes=SpikeTimes,
        BinSize=BinSize,
        Duration=Duration,
        Channels=Channels,
    )
    if len(Channels) == 1:
        Matrix = np.zeros((1, 1), dtype=float)
    else:
        Matrix = np.corrcoef(Counts)
        Matrix = np.nan_to_num(Matrix, nan=0.0, posinf=0.0, neginf=0.0)
    np.fill_diagonal(Matrix, 0.0)
    return Matrix, Channels, Counts, BinEdges


def _proportion_tiled(ReferenceTimes, TargetTimes, Dt):
    """Return the fraction of reference spikes within ``dt`` of target spikes."""
    if len(ReferenceTimes) == 0 or len(TargetTimes) == 0:
        return 0.0
    Target = np.asarray(TargetTimes)
    Count = 0
    for SpikeTime in ReferenceTimes:
        Left = np.searchsorted(Target, SpikeTime - Dt, side="left")
        Right = np.searchsorted(Target, SpikeTime + Dt, side="right")
        if Right > Left:
            Count += 1
    return Count / len(ReferenceTimes)


def _covered_time_fraction(SpikeTimes, Dt, Duration):
    """Return the fraction of recording time covered by ``dt`` windows."""
    if len(SpikeTimes) == 0 or Duration <= 0:
        return 0.0
    Intervals = np.column_stack(
        [
            np.maximum(0.0, np.asarray(SpikeTimes) - Dt),
            np.minimum(Duration, np.asarray(SpikeTimes) + Dt),
        ]
    )
    Intervals = Intervals[np.argsort(Intervals[:, 0])]
    Covered = 0.0
    CurrentStart, CurrentEnd = Intervals[0]
    for Start, End in Intervals[1:]:
        if Start <= CurrentEnd:
            CurrentEnd = max(CurrentEnd, End)
        else:
            Covered += CurrentEnd - CurrentStart
            CurrentStart, CurrentEnd = Start, End
    Covered += CurrentEnd - CurrentStart
    return Covered / Duration


def STTCPair(TimesA, TimesB, Dt=0.02, Duration=None):
    """Compute Spike Time Tiling Coefficient for one channel pair.

    STTC measures temporal association between two spike trains while correcting
    for firing rate and recording duration. Values are typically in ``[-1, 1]``:
    positive values indicate temporal co-occurrence within ``dt`` seconds, zero
    indicates little association, and negative values indicate avoidance.

    Parameters
    ----------
    times_a, times_b : array-like
        Spike times in seconds for two channels.
    dt : float
        Temporal tolerance window in seconds.
    duration : float, optional
        Recording duration in seconds. If omitted, inferred from the latest
        spike in the pair.

    Returns
    -------
    float
        STTC value for the two spike trains.
    """
    TimesA = np.asarray(TimesA, dtype=float)
    TimesB = np.asarray(TimesB, dtype=float)
    if Duration is None:
        MaxA = np.max(TimesA) if len(TimesA) else 0.0
        MaxB = np.max(TimesB) if len(TimesB) else 0.0
        Duration = max(MaxA, MaxB)
    if Duration <= 0 or len(TimesA) == 0 or len(TimesB) == 0:
        return 0.0

    Pa = _proportion_tiled(TimesA, TimesB, Dt)
    Pb = _proportion_tiled(TimesB, TimesA, Dt)
    Ta = _covered_time_fraction(TimesA, Dt, Duration)
    Tb = _covered_time_fraction(TimesB, Dt, Duration)

    DenA = 1 - Pa * Tb
    DenB = 1 - Pb * Ta
    TermA = 0.0 if DenA == 0 else (Pa - Tb) / DenA
    TermB = 0.0 if DenB == 0 else (Pb - Ta) / DenB
    return 0.5 * (TermA + TermB)


def STTCMatrix(SpikeTimes, Dt=0.02, Duration=None, Channels=None, Verbose=False):
    """Compute a symmetric STTC functional connectivity matrix.

    Parameters
    ----------
    spike_times : dict
        Mapping ``{channel: spike_times_seconds}``.
    dt : float
        STTC coincidence window in seconds.
    duration : float, optional
        Recording duration in seconds.
    channels : list[int], optional
        Channel order to use for matrix rows/columns.

    Returns
    -------
    tuple
        ``(matrix, channels)``.
    """
    Channels = sorted(SpikeTimes) if Channels is None else list(Channels)
    if Duration is None:
        MaxTimes = [np.max(Times) for Times in SpikeTimes.values() if len(Times) > 0]
        Duration = max(MaxTimes) if MaxTimes else 0.0

    Matrix = np.zeros((len(Channels), len(Channels)), dtype=float)
    TotalPairs = len(Channels) * (len(Channels) - 1) // 2
    CompletedPairs = 0
    ProgressStep = max(1, TotalPairs // 20)
    StartTime = time.time()

    for I, ChannelI in enumerate(Channels):
        for J in range(I + 1, len(Channels)):
            ChannelJ = Channels[J]
            Value = STTCPair(SpikeTimes.get(ChannelI, []), SpikeTimes.get(ChannelJ, []), Dt=Dt, Duration=Duration)
            Matrix[I, J] = Value
            Matrix[J, I] = Value
            CompletedPairs += 1

            if Verbose and (CompletedPairs % ProgressStep == 0 or CompletedPairs == TotalPairs):
                Percentage = 100.0 * CompletedPairs / TotalPairs if TotalPairs else 100.0
                Elapsed = time.time() - StartTime
                print(
                    f"  STTC: {CompletedPairs}/{TotalPairs} pairs "
                    f"({Percentage:.1f}%) - {Elapsed:.1f} s",
                    flush=True,
                )
    return Matrix, Channels


def CrossCorrelogramPeakMatrix(SpikeTimes, MaxLag=0.1, BinSize=0.005, Channels=None):
    """Compute peak cross-correlogram counts and peak lags for channel pairs.

    For each ordered channel pair ``i -> j``, spike-time differences
    ``time_j - time_i`` are histogrammed within ``[-max_lag, max_lag]``. The
    peak matrix stores the maximum bin count and the lag matrix stores the lag
    center of that peak.

    Parameters
    ----------
    spike_times : dict
        Mapping ``{channel: spike_times_seconds}``.
    max_lag : float
        Maximum lag in seconds on each side of zero.
    bin_size : float
        Correlogram bin size in seconds.
    channels : list[int], optional
        Channel order to use for matrix rows/columns.

    Returns
    -------
    tuple
        ``(peak_matrix, lag_matrix, channels)``. ``peak_matrix[i, j]`` is the
        maximum count in the correlogram from channel i to channel j; the
        matching lag is stored in ``lag_matrix[i, j]``.
    """
    Channels = sorted(SpikeTimes) if Channels is None else list(Channels)
    LagEdges = np.arange(-MaxLag, MaxLag + BinSize, BinSize)
    LagCenters = (LagEdges[:-1] + LagEdges[1:]) / 2
    Peak = np.zeros((len(Channels), len(Channels)), dtype=float)
    Lag = np.zeros((len(Channels), len(Channels)), dtype=float)

    for I, ChannelI in enumerate(Channels):
        TimesI = np.asarray(SpikeTimes.get(ChannelI, []), dtype=float)
        for J, ChannelJ in enumerate(Channels):
            if I == J:
                continue
            TimesJ = np.asarray(SpikeTimes.get(ChannelJ, []), dtype=float)
            Differences = []
            for SpikeTime in TimesI:
                Left = np.searchsorted(TimesJ, SpikeTime - MaxLag, side="left")
                Right = np.searchsorted(TimesJ, SpikeTime + MaxLag, side="right")
                Differences.extend(TimesJ[Left:Right] - SpikeTime)
            if not Differences:
                continue
            Hist, _ = np.histogram(Differences, bins=LagEdges)
            PeakIndex = int(np.argmax(Hist))
            Peak[I, J] = Hist[PeakIndex]
            Lag[I, J] = LagCenters[PeakIndex]

    return Peak, Lag, Channels


def ThresholdMatrix(Matrix, Threshold, Absolute=True, KeepDiagonal=False):
    """Threshold a connectivity matrix into a binary adjacency matrix.

    Parameters
    ----------
    matrix : array-like
        Weighted connectivity matrix.
    threshold : float
        Minimum score required for an edge.
    absolute : bool
        If True, threshold absolute values. If False, threshold signed values.
    keep_diagonal : bool
        If False, force the diagonal to zero.

    Returns
    -------
    numpy.ndarray
        Binary adjacency matrix with the same shape as ``matrix``.
    """
    Values = np.abs(Matrix) if Absolute else Matrix
    Adjacency = (Values >= Threshold).astype(int)
    if not KeepDiagonal:
        np.fill_diagonal(Adjacency, 0)
    return Adjacency


def MatrixToEdges(Matrix, Channels, Threshold=None, Absolute=True, Directed=False):
    """Convert a weighted connectivity matrix to an edge table.

    Parameters
    ----------
    matrix : array-like
        Weighted connectivity matrix.
    channels : list[int]
        Channel ids corresponding to matrix rows/columns.
    threshold : float, optional
        If provided, keep only edges whose score is at least this value.
    absolute : bool
        If True, apply threshold to absolute weights.
    directed : bool
        If False, return only the upper triangle. If True, return all
        off-diagonal directed pairs.

    Returns
    -------
    pandas.DataFrame
        Columns ``source``, ``target``, and ``weight``.
    """
    Rows = []
    for I, Source in enumerate(Channels):
        Start = 0 if Directed else I + 1
        for J in range(Start, len(Channels)):
            if I == J:
                continue
            Weight = Matrix[I, J]
            Score = abs(Weight) if Absolute else Weight
            if Threshold is not None and Score < Threshold:
                continue
            Rows.append({"source": Source, "target": Channels[J], "weight": Weight})
    return pd.DataFrame(Rows)


def NodeStrength(Matrix, Channels, Absolute=True):
    """Compute weighted node strength for each channel.

    Node strength is the sum of edge weights connected to each channel. By
    default absolute weights are used, which is usually appropriate for signed
    correlation-like matrices.
    """
    Values = np.abs(Matrix) if Absolute else Matrix.copy()
    np.fill_diagonal(Values, 0.0)
    return pd.DataFrame({"channel": Channels, "strength": np.sum(Values, axis=1)})


def AnalyzeSpikeDir(
    SpikeDir,
    SamplingRate,
    Duration=None,
    IncludeLabels=None,
    BinSize=0.05,
    STTCDt=0.02,
    CorrThreshold=None,
    STTCThreshold=None,
    MinFiringRateHz=0.25,
    ExcludedChannels=None,
    Verbose=True,
):
    """Run a compact connectivity analysis for one processed recording.

    This convenience wrapper loads ``frames_ch*.npy`` files, converts frames to
    seconds, computes spike-count correlation and STTC matrices, and optionally
    thresholds those matrices into adjacency/edge tables.

    Parameters
    ----------
    spike_dir : str or pathlib.Path
        processed recording folder containing ``frames_ch*.npy``.
    sampling_rate : float
        sampling rate used to convert frames to seconds.
    duration : float, optional
        duration in seconds. If omitted, inferred from spike frames.
    include_labels : list[int], optional
        Detector labels to keep, for example to include only negative or
        positive spikes when ``label_ch*.npy`` files are available.
    bin_size : float
        Bin size in seconds for spike-count correlation.
    sttc_dt : float
        STTC coincidence window in seconds.
    corr_threshold : float, optional
        If provided, add thresholded correlation adjacency and edge table.
    sttc_threshold : float, optional
        If provided, add thresholded STTC adjacency and edge table.

    Returns
    -------
    dict
        Dictionary containing channel order, raw spike frames/times, binned
        counts, bin edges, correlation/STTC matrices, node-strength tables, and
        optional adjacency/edge tables.
    """
    StartTime = time.time()
    if Verbose:
        print(f"Loading spikes from: {SpikeDir}", flush=True)

    SpikeFrames = LoadSpikeFrames(SpikeDir, IncludeLabels=IncludeLabels)
    ExcludedChannels = set() if ExcludedChannels is None else set(ExcludedChannels)
    if ExcludedChannels:
        SpikeFrames = {
            Channel: Frames
            for Channel, Frames in SpikeFrames.items()
            if Channel not in ExcludedChannels
        }
        if Verbose:
            print(
                f"Excluded channels: {sorted(ExcludedChannels)}; "
                f"{len(SpikeFrames)} channels remaining",
                flush=True,
            )
        if not SpikeFrames:
            raise ValueError("No channels remain after applying ExcludedChannels.")

    SpikeTimes = FramesToSeconds(SpikeFrames, SamplingRate=SamplingRate)
    if Verbose:
        TotalSpikes = sum(len(Frames) for Frames in SpikeFrames.values())
        print(
            f"Loaded {len(SpikeFrames)} channels and {TotalSpikes} spikes "
            f"in {time.time() - StartTime:.1f} s",
            flush=True,
        )

    if Duration is None:
        MaxTimes = [np.max(Times) for Times in SpikeTimes.values() if len(Times) > 0]
        Duration = max(MaxTimes) if MaxTimes else 0.0

    if Duration <= 0:
        raise ValueError("Duration must be positive to calculate channel firing rates.")

    FiringRates = {
        Channel: len(Times) / Duration
        for Channel, Times in SpikeTimes.items()
    }
    if MinFiringRateHz is not None:
        ActiveChannels = [
            Channel
            for Channel, FiringRate in FiringRates.items()
            if FiringRate > MinFiringRateHz
        ]
        SpikeFrames = {Channel: SpikeFrames[Channel] for Channel in ActiveChannels}
        SpikeTimes = {Channel: SpikeTimes[Channel] for Channel in ActiveChannels}

        if Verbose:
            ExcludedChannels = len(FiringRates) - len(ActiveChannels)
            print(
                f"Active-channel filter: {len(ActiveChannels)} retained, "
                f"{ExcludedChannels} excluded "
                f"(firing rate <= {MinFiringRateHz} Hz)",
                flush=True,
            )

        if not ActiveChannels:
            raise ValueError(
                f"No channels have a firing rate greater than {MinFiringRateHz} Hz."
            )

    CorrelationStartTime = time.time()
    if Verbose:
        print("Computing spike-count correlation...", flush=True)
    Corr, Channels, Counts, BinEdges = SpikeCountCorrelation(
        SpikeTimes,
        BinSize=BinSize,
        Duration=Duration,
    )
    if Verbose:
        print(f"Correlation completed in {time.time() - CorrelationStartTime:.1f} s", flush=True)

    STTCStartTime = time.time()
    if Verbose:
        TotalPairs = len(Channels) * (len(Channels) - 1) // 2
        print(f"Computing STTC for {TotalPairs} channel pairs...", flush=True)
    STTC, _ = STTCMatrix(
        SpikeTimes,
        Dt=STTCDt,
        Duration=Duration,
        Channels=Channels,
        Verbose=Verbose,
    )
    if Verbose:
        print(f"STTC completed in {time.time() - STTCStartTime:.1f} s", flush=True)

    Result = {
        "channels": Channels,
        "spike_frames": SpikeFrames,
        "spike_times": SpikeTimes,
        "channel_firing_rates": pd.DataFrame(
            {
                "channel": list(FiringRates),
                "firing_rate_hz": list(FiringRates.values()),
                "is_active": [
                    MinFiringRateHz is None or FiringRate > MinFiringRateHz
                    for FiringRate in FiringRates.values()
                ],
            }
        ),
        "counts": Counts,
        "bin_edges": BinEdges,
        "correlation_matrix": Corr,
        "sttc_matrix": STTC,
        "correlation_strength": NodeStrength(Corr, Channels),
        "sttc_strength": NodeStrength(STTC, Channels),
    }
    if CorrThreshold is not None:
        Result["correlation_adjacency"] = ThresholdMatrix(Corr, CorrThreshold)
        Result["correlation_edges"] = MatrixToEdges(Corr, Channels, Threshold=CorrThreshold)
    if STTCThreshold is not None:
        Result["sttc_adjacency"] = ThresholdMatrix(STTC, STTCThreshold)
        Result["sttc_edges"] = MatrixToEdges(STTC, Channels, Threshold=STTCThreshold)

    if Verbose:
        print(f"Analysis completed in {time.time() - StartTime:.1f} s", flush=True)

    return Result


# Backward-compatible aliases for code written before the public API was
# aligned with the PascalCase convention used by the other brain_3d modules.
load_spike_frames = LoadSpikeFrames
frames_to_seconds = FramesToSeconds
bin_spike_counts = BinSpikeCounts
spike_count_correlation = SpikeCountCorrelation
sttc_pair = STTCPair
sttc_matrix = STTCMatrix
cross_correlogram_peak_matrix = CrossCorrelogramPeakMatrix
threshold_matrix = ThresholdMatrix
matrix_to_edges = MatrixToEdges
node_strength = NodeStrength
analyze_spike_dir = AnalyzeSpikeDir
